# Generated by Django 6.0.3 on 2026-04-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeros', models.JSONField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Previsao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('numeros_previstos', models.JSONField()),
                ('probabilidades', models.JSONField(blank=True, null=True)),
                ('numeros_reais', models.JSONField(blank=True, null=True)),
                ('acertos', models.IntegerField(blank=True, null=True)),
                ('taxa_acerto', models.FloatField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nao_repete', models.JSONField()),
                ('repete', models.JSONField()),
                ('falta', models.JSONField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
