# Generated by Django 6.0.3 on 2026-04-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsao',
            name='acuracia',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
